mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
     # ex: /polls/
    path('', views.short_index, name='index'),
    path('home/', views.index, name='index-login'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='details'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.user_logout, name='logout'),
    path('filter/', views.question_filter, name='question_filter')
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser, UserManager

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class CustomUserManager(UserManager):
    pass

class UserInfo(AbstractUser):
    objects = CustomUserManager()
    email = models.EmailField(max_length=50, unique=True)
    username = models.CharField(max_length=100, unique=True)
    country = models.CharField(max_length=50, default='Mexico')
    #date = models.DateField('Fecha de nacimiento')

    def __str__(self):
        return self.email

class Category(models.Model):
    category_name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.category_name

class Product(models.Model):
    product_name = models.CharField(max_length=75)
    product_price = models.DecimalField(decimal_places=2, max_digits=9)
    product_pub = models.DateTimeField('date published')
    product_image = models.ImageField(upload_to = 'pic_folder')
    product_description = models.CharField(max_length=150)
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.product_name

polls/forms.py
from django import forms
from polls.models import UserInfo, Product, Category
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CUserLoginForm(UserCreationForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta(UserCreationForm):
        model = UserInfo
        fields = ('email','password')

class CUserRegisterForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = UserInfo
        fields = ('username','password','email','country')

class CUserChangeForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = UserInfo
        fields = ('email','username','country')

class ProductForm(forms.Form):
    class Meta:
        model = Product

class CategoryForm(forms.Form):
    class Meta:
        model = Category

polls/views.py
from django.views.generic import CreateView

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Question, Choice, UserInfo
# Library to load HTML content
from django.template import loader
from django.shortcuts import get_object_or_404,render
# Library to handle errors
from django.http import Http404

from polls.forms import CUserLoginForm, CUserRegisterForm, CUserChangeForm, ProductForm, CategoryForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from datetime import datetime

#Pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

@login_required
def index(request):
        latest_question_list = Question.objects.order_by('-pub_date')
        page_number = request.GET.get('page', 1)

        paginate_result = do_paginate(latest_question_list, page_number)
        latest_question_list = paginate_result[0]
        paginator = paginate_result[1]
        base_url = '?'
        return render(request, 'polls/quiz.html',
                        {'latest_question_list': latest_question_list, 'paginator' : paginator, 'base_url': base_url})

def short_index(request):
        latest_question_list = Question.objects.order_by('-pub_date')[:5]
        context = {'latest_question_list': latest_question_list}
        return render(request, 'polls/index.html', context)

def index2(request):
        return HttpResponse("Buenos días")

def detail(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        try:
            chioces = question.choice_set.get(pk=question_id)
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'error_message': "You didn't select a choice.",
            })
        else:
            return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

#Login section
@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:index'))

def register_user(request):
    registered = False
    if request.method == 'POST':
        profile_form = CUserChangeForm(data=request.POST)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            if 'username' in request.FILES:
                print('found it')
                profile.username = request.FILES['username']
            profile.save()
            registered = True
        else:
            print(profile_form.errors)
    else:
        profile_form = CUserChangeForm()
    return render(request,'polls/registration.html',
                          {'profile_form':profile_form,
                           'registered':registered})

def register_product(request):
    if request.method == 'POST':
        product_form = ProductForm(data=request.POST)
        if product_form.is_valid():
            product = product_form.save(commit=False)
            product.save()
        else:
            print(product_form.errors)
    else:
        product_form = ProductForm()
    return render(request,'polls/product.html',
                          {'product_form':product_form})

def login_user(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        try:
            user = UserInfo.objects.get(email=email)
            print(user)
            if user:
                login(request,user)
                return HttpResponseRedirect(reverse('polls:index-login'))
        except:
            print("Someone tried to login and failed.")
            print("They used email: {} and password: {}".format(email,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'polls/login.html', {})

@login_required
def question_filter(request):
    question = request.POST.get('question_text', '').strip()
    question_date = request.POST.get('question_date', '').strip()
    print(question_date)
    if len(question) == 0:
        question = request.GET.get('question_text', '').strip()
    if len(question_date) == 0:
        question_date = datetime.now()
    question_list = Question.objects.filter(question_text__contains=question, pub_date__date=question_date).order_by('-pub_date')
    page_number = request.GET.get('page', 1)
    paginate_result = do_paginate(question_list, page_number)
    question_list = paginate_result[0]
    paginator = paginate_result[1]
    base_url = '/polls/filter/?question_text=' + question + "&question_date=" + question_date + '&'
    return render(request, 'polls/quiz.html',
                      {'latest_question_list': question_list, 'paginator' : paginator, 'base_url': base_url, 'search_question': question, 'search_date': question_date})

def do_paginate(data_list, page_number):
    ret_data_list = data_list
    # suppose we display at most 2 records in each page.
    result_per_page = 2
    # build the paginator object.
    paginator = Paginator(data_list, result_per_page)
    try:
        # get data list for the specified page_number.
        ret_data_list = paginator.page(page_number)
    except EmptyPage:
        # get the lat page data if the page_number is bigger than last page number.
        ret_data_list = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        # if the page_number is not an integer then return the first page data.
        ret_data_list = paginator.page(1)
    return [ret_data_list, paginator]

polls/templates/polls/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>App Quiz</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

      {# Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'polls:index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'polls:register' %}">Registro</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'polls:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'polls:login_user' %}">Login</a></li>
          {% endif %}

</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Bienvenido a Quiz App !</h1>
    {% if user.is_authenticated %}
        <h2>Hola {{ user.username }}</h2>

    {% else %}
        <h2>Regístrate o inicia sesión</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

polls/templates/polls/login.html
{% extends 'polls/base.html' %}
{% block body_block %}
{% load static %}
<div>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<form class="form-signin" method="post" action="{% url 'polls:login_user' %}">
    {% csrf_token %}
    {% load static %}
    <img id="icon" class="mb-4" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Iniciar sesión</h1>
    <label for="inputEmail" class="sr-only">Email</label>
    <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Email address" required="" autofocus="">
    <label for="inputPassword" class="sr-only">Contraseña</label>
    <input type="password" id="inputPassword" name="password"  class="form-control" placeholder="Password" required="">
    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Recordarme
      </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Ingresar</button>
  </form>
</div>
  {% endblock %}

polls/templates/polls/product.html
{% extends "polls/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        <h1>Productos</h1>
        <h3>Complete el formulario</h3>

    <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ product_form.as_p }}
          <input type="submit" name="" value="Agregar producto">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

polls/templates/polls/quiz.html
{% extends "polls/base.html" %}

{% block body_block %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<div class="page-header">
  <div id="navbar" class="navbar-collapse collapse">
      <form class="navbar-form" method="post" action="{% url 'polls:question_filter' %}">
             <!-- avoid CSRF verification failed error. -->
             {% csrf_token %}
          <div class="form-group">
             <input name="question_text" type="text" placeholder="Question text" class="form-control" value="{{ search_question }}">
             <input name="question_date" type="date" class="form-control" value="{{ search_date }}">
          </div>
          <button type="submit" class="btn btn-success">Search</button>
      </form>
  </div>
</div>

<div class="container">
    <h1>Preguntas </h1>
    {% if user.is_authenticated %}
        <h2>Bienvenido {{ user.username }}</h2>

        {% if latest_question_list %}
            <ul>
            {% for question in latest_question_list %}
            <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    {% else %}
        <h2>Regístrate o inicia sesión</h2>
    {% endif %}
</div>

<ul class="pagination">
  <!-- previous page link -->
  {% if latest_question_list.has_previous %}
      <li><a href="{{ base_url }}page={{ latest_question_list.previous_page_number }}">&laquo;</a></li>
  {% else %}
      <li class="disabled"><span>&laquo;</span></li>
  {% endif %}
  <!-- page number link-->
  {% for i in paginator.page_range %}
       {% if latest_question_list.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
       {% else %}
          <li><a href="{{ base_url }}page={{ i }}">{{ i }}</a></li>
       {% endif %}
  {% endfor %}
  <!-- next page link -->
  {% if latest_question_list.has_next %}

      <li><a href="{{ base_url }}page={{ latest_question_list.next_page_number }}">&raquo;</a></li>
  {% else %}
      <li class="disabled"><span>&raquo;</span></li>
  {% endif %}
</ul>


{% endblock %}

polls/templates/polls/registration.html
{% extends "polls/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Gracias. Ahora incie sesión</h1>
      {% else %}
        <h1>Registro</h1>
        <h3>Complete el formulario</h3>

    <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}">Vote again?</a>